//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AP_StockPromotion_V1.ws_authorize
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AuthorizeSoap", Namespace="http://tempuri.org/")]
    public partial class Authorize : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthorizeSoapHeader authorizeSoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback UserLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCurrentDomainOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindUserProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindUserProjectByUserIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindUserProjectByUserNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindUserAppUserIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindUserAppUserNameOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Authorize() {
            this.Url = global::AP_StockPromotion_V1.Properties.Settings.Default.AP_StockPromotion_V1_ws_authorize_Authorize;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthorizeSoapHeader AuthorizeSoapHeaderValue {
            get {
                return this.authorizeSoapHeaderValueField;
            }
            set {
                this.authorizeSoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UserLoginCompletedEventHandler UserLoginCompleted;
        
        /// <remarks/>
        public event GetCurrentDomainCompletedEventHandler GetCurrentDomainCompleted;
        
        /// <remarks/>
        public event FindUserProfileCompletedEventHandler FindUserProfileCompleted;
        
        /// <remarks/>
        public event FindUserProjectByUserIDCompletedEventHandler FindUserProjectByUserIDCompleted;
        
        /// <remarks/>
        public event FindUserProjectByUserNameCompletedEventHandler FindUserProjectByUserNameCompleted;
        
        /// <remarks/>
        public event FindUserAppUserIDCompletedEventHandler FindUserAppUserIDCompleted;
        
        /// <remarks/>
        public event FindUserAppUserNameCompletedEventHandler FindUserAppUserNameCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthorizeSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UserLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AutorizeData UserLogin(string User, string Password, string AppCode) {
            object[] results = this.Invoke("UserLogin", new object[] {
                        User,
                        Password,
                        AppCode});
            return ((AutorizeData)(results[0]));
        }
       

        /// <remarks/>
        public void UserLoginAsync(string User, string Password, string AppCode) {
            this.UserLoginAsync(User, Password, AppCode, null);
        }
        
        /// <remarks/>
        public void UserLoginAsync(string User, string Password, string AppCode, object userState) {
            if ((this.UserLoginOperationCompleted == null)) {
                this.UserLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserLoginOperationCompleted);
            }
            this.InvokeAsync("UserLogin", new object[] {
                        User,
                        Password,
                        AppCode}, this.UserLoginOperationCompleted, userState);
        }
        
        private void OnUserLoginOperationCompleted(object arg) {
            if ((this.UserLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserLoginCompleted(this, new UserLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthorizeSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCurrentDomain", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCurrentDomain() {
            object[] results = this.Invoke("GetCurrentDomain", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCurrentDomainAsync() {
            this.GetCurrentDomainAsync(null);
        }
        
        /// <remarks/>
        public void GetCurrentDomainAsync(object userState) {
            if ((this.GetCurrentDomainOperationCompleted == null)) {
                this.GetCurrentDomainOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCurrentDomainOperationCompleted);
            }
            this.InvokeAsync("GetCurrentDomain", new object[0], this.GetCurrentDomainOperationCompleted, userState);
        }
        
        private void OnGetCurrentDomainOperationCompleted(object arg) {
            if ((this.GetCurrentDomainCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCurrentDomainCompleted(this, new GetCurrentDomainCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthorizeSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindUserProfile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AutorizeData FindUserProfile(string User, string AppCode) {
            object[] results = this.Invoke("FindUserProfile", new object[] {
                        User,
                        AppCode});
            return ((AutorizeData)(results[0]));
        }
        
        /// <remarks/>
        public void FindUserProfileAsync(string User, string AppCode) {
            this.FindUserProfileAsync(User, AppCode, null);
        }
        
        /// <remarks/>
        public void FindUserProfileAsync(string User, string AppCode, object userState) {
            if ((this.FindUserProfileOperationCompleted == null)) {
                this.FindUserProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindUserProfileOperationCompleted);
            }
            this.InvokeAsync("FindUserProfile", new object[] {
                        User,
                        AppCode}, this.FindUserProfileOperationCompleted, userState);
        }
        
        private void OnFindUserProfileOperationCompleted(object arg) {
            if ((this.FindUserProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindUserProfileCompleted(this, new FindUserProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthorizeSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindUserProjectByUserID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public _UserProjectData FindUserProjectByUserID(string User) {
            object[] results = this.Invoke("FindUserProjectByUserID", new object[] {
                        User});
            return ((_UserProjectData)(results[0]));
        }
        
        /// <remarks/>
        public void FindUserProjectByUserIDAsync(string User) {
            this.FindUserProjectByUserIDAsync(User, null);
        }
        
        /// <remarks/>
        public void FindUserProjectByUserIDAsync(string User, object userState) {
            if ((this.FindUserProjectByUserIDOperationCompleted == null)) {
                this.FindUserProjectByUserIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindUserProjectByUserIDOperationCompleted);
            }
            this.InvokeAsync("FindUserProjectByUserID", new object[] {
                        User}, this.FindUserProjectByUserIDOperationCompleted, userState);
        }
        
        private void OnFindUserProjectByUserIDOperationCompleted(object arg) {
            if ((this.FindUserProjectByUserIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindUserProjectByUserIDCompleted(this, new FindUserProjectByUserIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthorizeSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindUserProjectByUserName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public _UserProjectData FindUserProjectByUserName(string User) {
            object[] results = this.Invoke("FindUserProjectByUserName", new object[] {
                        User});
            return ((_UserProjectData)(results[0]));
        }
        
        /// <remarks/>
        public void FindUserProjectByUserNameAsync(string User) {
            this.FindUserProjectByUserNameAsync(User, null);
        }
        
        /// <remarks/>
        public void FindUserProjectByUserNameAsync(string User, object userState) {
            if ((this.FindUserProjectByUserNameOperationCompleted == null)) {
                this.FindUserProjectByUserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindUserProjectByUserNameOperationCompleted);
            }
            this.InvokeAsync("FindUserProjectByUserName", new object[] {
                        User}, this.FindUserProjectByUserNameOperationCompleted, userState);
        }
        
        private void OnFindUserProjectByUserNameOperationCompleted(object arg) {
            if ((this.FindUserProjectByUserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindUserProjectByUserNameCompleted(this, new FindUserProjectByUserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthorizeSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindUserAppUserID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public _UserAppData FindUserAppUserID(string User) {
            object[] results = this.Invoke("FindUserAppUserID", new object[] {
                        User});
            return ((_UserAppData)(results[0]));
        }
        
        /// <remarks/>
        public void FindUserAppUserIDAsync(string User) {
            this.FindUserAppUserIDAsync(User, null);
        }
        
        /// <remarks/>
        public void FindUserAppUserIDAsync(string User, object userState) {
            if ((this.FindUserAppUserIDOperationCompleted == null)) {
                this.FindUserAppUserIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindUserAppUserIDOperationCompleted);
            }
            this.InvokeAsync("FindUserAppUserID", new object[] {
                        User}, this.FindUserAppUserIDOperationCompleted, userState);
        }
        
        private void OnFindUserAppUserIDOperationCompleted(object arg) {
            if ((this.FindUserAppUserIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindUserAppUserIDCompleted(this, new FindUserAppUserIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthorizeSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindUserAppUserName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public _UserAppData FindUserAppUserName(string User) {
            object[] results = this.Invoke("FindUserAppUserName", new object[] {
                        User});
            return ((_UserAppData)(results[0]));
        }
        
        /// <remarks/>
        public void FindUserAppUserNameAsync(string User) {
            this.FindUserAppUserNameAsync(User, null);
        }
        
        /// <remarks/>
        public void FindUserAppUserNameAsync(string User, object userState) {
            if ((this.FindUserAppUserNameOperationCompleted == null)) {
                this.FindUserAppUserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindUserAppUserNameOperationCompleted);
            }
            this.InvokeAsync("FindUserAppUserName", new object[] {
                        User}, this.FindUserAppUserNameOperationCompleted, userState);
        }
        
        private void OnFindUserAppUserNameOperationCompleted(object arg) {
            if ((this.FindUserAppUserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindUserAppUserNameCompleted(this, new FindUserAppUserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class AuthorizeSoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class _UserAppData {
        
        private string _UserAppField;
        
        /// <remarks/>
        public string _UserApp {
            get {
                return this._UserAppField;
            }
            set {
                this._UserAppField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class _UserProjectData {
        
        private string _UserProjectField;
        
        /// <remarks/>
        public string _UserProject {
            get {
                return this._UserProjectField;
            }
            set {
                this._UserProjectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AutorizeData {
        
        private bool loginResultField;
        
        private string userPrincipalNameField;
        
        private string domainUserNameField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string displayNameField;
        
        private string employeeIDField;
        
        private string emailField;
        
        private string divisionField;
        
        private System.Nullable<System.DateTime> accountExpirationDateField;
        
        private System.Nullable<System.DateTime> lastLogonField;
        
        private string authenticationProviderField;
        
        private string sysUserIdField;
        
        private string sysUserDataField;
        
        private string sysUserRolesField;
        
        private string sysAppCodeField;
        
        private string userProjectField;
        
        private string userAppField;
        
        /// <remarks/>
        public bool LoginResult {
            get {
                return this.loginResultField;
            }
            set {
                this.loginResultField = value;
            }
        }
        
        /// <remarks/>
        public string UserPrincipalName {
            get {
                return this.userPrincipalNameField;
            }
            set {
                this.userPrincipalNameField = value;
            }
        }
        
        /// <remarks/>
        public string DomainUserName {
            get {
                return this.domainUserNameField;
            }
            set {
                this.domainUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public string EmployeeID {
            get {
                return this.employeeIDField;
            }
            set {
                this.employeeIDField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> AccountExpirationDate {
            get {
                return this.accountExpirationDateField;
            }
            set {
                this.accountExpirationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastLogon {
            get {
                return this.lastLogonField;
            }
            set {
                this.lastLogonField = value;
            }
        }
        
        /// <remarks/>
        public string AuthenticationProvider {
            get {
                return this.authenticationProviderField;
            }
            set {
                this.authenticationProviderField = value;
            }
        }
        
        /// <remarks/>
        public string SysUserId {
            get {
                return this.sysUserIdField;
            }
            set {
                this.sysUserIdField = value;
            }
        }
        
        /// <remarks/>
        public string SysUserData {
            get {
                return this.sysUserDataField;
            }
            set {
                this.sysUserDataField = value;
            }
        }
        
        /// <remarks/>
        public string SysUserRoles {
            get {
                return this.sysUserRolesField;
            }
            set {
                this.sysUserRolesField = value;
            }
        }
        
        /// <remarks/>
        public string SysAppCode {
            get {
                return this.sysAppCodeField;
            }
            set {
                this.sysAppCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UserProject {
            get {
                return this.userProjectField;
            }
            set {
                this.userProjectField = value;
            }
        }
        
        /// <remarks/>
        public string UserApp {
            get {
                return this.userAppField;
            }
            set {
                this.userAppField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UserLoginCompletedEventHandler(object sender, UserLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AutorizeData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AutorizeData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetCurrentDomainCompletedEventHandler(object sender, GetCurrentDomainCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCurrentDomainCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCurrentDomainCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void FindUserProfileCompletedEventHandler(object sender, FindUserProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindUserProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindUserProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AutorizeData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AutorizeData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void FindUserProjectByUserIDCompletedEventHandler(object sender, FindUserProjectByUserIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindUserProjectByUserIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindUserProjectByUserIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public _UserProjectData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((_UserProjectData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void FindUserProjectByUserNameCompletedEventHandler(object sender, FindUserProjectByUserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindUserProjectByUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindUserProjectByUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public _UserProjectData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((_UserProjectData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void FindUserAppUserIDCompletedEventHandler(object sender, FindUserAppUserIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindUserAppUserIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindUserAppUserIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public _UserAppData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((_UserAppData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void FindUserAppUserNameCompletedEventHandler(object sender, FindUserAppUserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindUserAppUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindUserAppUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public _UserAppData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((_UserAppData)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591